<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Entities\ValueObjects\" />
      <Folder Include="Entities\Enumerations\" />
      <Folder Include="Entities\Interfaces\" />
      <Folder Include="Entities\Events\" />
      <Folder Include="Common\Interfaces\" />
      <Folder Include="Common\Concrete\" />
      <Folder Include="Helpers\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Specification" Version="1.0.1" />
    </ItemGroup>

</Project>